### ISSUE TITLE
EasySearch Components breaks #each ... in ... syntax

### ISSUE THREAD

**Issue by veered** [matteodem/meteor-easy-search#331] opened 2015-10-27 00:09 UTC
I originally installed `easy:core` and the `#each ... in ...` syntax in Blaze stopped working. I eventually guessed that Blaze Components might be the culprit. I switched to `easysearch:core` which removed Blaze Components and everything started working again. Right now EasySearch has pinned an old version of Blaze Components. Maybe it needs to be upgraded?

**Comment by rjsmith** [comment] 2015-10-27 19:47
Hi, I spotted the same problem. I have raised an issue on the Blaze Components repo

**Comment by mitar** [comment] 2015-10-27 20:10
That is the issue with how Blaze implemented that feature. See:
* https://github.com/peerlibrary/meteor-blaze-components/issues/100
* https://github.com/peerlibrary/meteor-blaze-components/issues/76
* https://github.com/meteor/meteor/issues/5280

But if I understand correctly, things stop working on other templates? This is very strange. :-)

**Comment by mitar** [comment] 2015-10-27 20:12
Sorry, ignore. I see that you are saying that other templates stop working when you add Blaze Components. I will look into this.

**Comment by mitar** [comment] 2015-10-28 03:31
Fixed in Blaze Components  0.15.1. Sorry for that.

**Comment by matteodem** [comment] 2015-10-28 14:40
thanks, the package version should be automatically updated. Will test that later

**Comment by rjsmith** [comment] 2015-10-28 18:52
Hi,
Good news. I force-upgraded my application to use peerlibrary:blaze-components@0.15.1, and the problem with #each .. in has been fixed .. all my templates look OK again. And the search components work too.

**Comment by dburles** [comment] 2015-10-29 00:55
works for me :)

**Comment by matteodem** [comment] 2015-10-29 11:40
Cool

**Closed by matteodem** 2015-10-29 11:40 UTC
Labels: bug

**Comment by mitar** [comment] 2015-10-29 17:40
You should probably update the dependency?

**Comment by matteodem** [comment] 2015-10-29 21:10
Is it really needed (since it's a minor version upgrade and meteor assumes semver)? I'll have a look if you tell me otherwise :smile:

**Comment by mitar** [comment] 2015-10-31 06:33
The issue is that the package depends on `peerlibrary:blaze-components@0.13.0'`. So I do not think Meteor will just automatically upgrade to `0.15.1` unless forced by some other package.

**Comment by matteodem** [comment] 2015-11-01 18:33
okay, I'll change that in another issue.
