### ISSUE TITLE
Method/Fxn to refreshing the search result

### ISSUE THREAD

**Issue by zyonnetworks** [matteodem/meteor-easy-search#557] opened 2016-11-26 22:53 UTC
Is there a feature to refresh the search results because when a new document is added, it puts it on the bottom even though sort if set to put newest records on top. It doesn't order correctly until I refresh the page.

**Comment by matteodem** [comment] 2016-11-28 08:36
duplicate of #513

**Closed by matteodem** 2016-11-28 08:36 UTC
