### ISSUE TITLE
Publication does not include recently added documents

### ISSUE THREAD

**Issue by HaNdTriX** [matteodem/meteor-easy-search#230] opened 2015-06-23 08:47 UTC
Hey @matteodem first of all thanks for the great package!

* * *

When you add new documents to a collection they will not be reflected in the reactive search results.

This is because the [observer](https://github.com/matteodem/meteor-easy-search/blob/master/lib/easy-search-common.js#L98) only observes documents that where present, when the `setUpPublication`  function got called.

      publishHandle = opts.collection
        .find({ 
          // This restriction causes the bug :(
          $or: resultArray 
        }, findOptions)
        .observe({
          // only gets called once for every document
          added: function (doc) { 
            doc._index = name;
            doc._sortedOrder = resultIds.indexOf(doc._id);
            publishScope.added('esSearchResults', doc._id, doc);
          },
          changed: function (doc) {
            doc._sortedOrder = resultIds.indexOf(doc._id);
            publishScope.changed('esSearchResults', doc._id, doc);
          },
          removed: function (doc) {
            publishScope.removed('esSearchResults', doc._id);
          }
        }
      );

https://github.com/matteodem/meteor-easy-search/blob/master/lib/easy-search-common.js#L98

**Comment by matteodem** [comment] 2015-06-28 13:45
That's right. The current way searching is being done revolves around only changing the content of the search results, but not the results themselves. I'll probably change that to be truly "reactive" some time soon.

I'll have this open for now.

**Comment by matteodem** [comment] 2015-07-14 16:13
I'll close this as it's a dupe of #151

**Closed by matteodem** 2015-07-14 16:13 UTC
Labels: feature
