### ISSUE TITLE
How do you search the default Meteor.users collection?

### ISSUE THREAD

**Issue by connor-baer** [matteodem/meteor-easy-search#155] opened 2015-02-24 12:17 UTC
Hello,

I'm trying to search through the default Meteor.users collection with the username as the search query. I set up everything as you would with any other collection but when I start typing in the search field, the console show the following error: 

Uncaught Error: Match error: Expected number, got undefined

This is my code on the both server an client: 

```
Meteor.users.initEasySearch(['username'], {
    'limit' : 10,
    'use' : 'mongo-db'
});
```

And my client html:

```
<div class="list">
      <div class="item item-input-inset">
        <label class="item-input-wrapper">
          {{> esInput index="meteor.users" placeholder="Enter a username..." }}
        </label>
      </div>
      <ul>
          {{#esEach index="meteor.users"}}
              <li>{{username}}</li>
          {{/esEach}}
      </ul>

      {{> esLoadMoreButton index="meteor.users"}}

      {{#ifEsHasNoResults index="meteor.users"}}
          <div class="no-results">No results found!</div>
      {{/ifEsHasNoResults}}

      {{#ifEsIsSearching index="meteor.users"}}
              <div>Loading...</div>
      {{/ifEsIsSearching}}

</div>
```

Is there anything else I need to do or change to make it work?

Thanks in advance for your help!

**Comment by matteodem** [comment] 2015-02-24 15:30
This is a duplicate of #137. I will document it soon

**Closed by matteodem** 2015-02-24 15:30 UTC
Labels: question
