### ISSUE TITLE
Easy search seems to be breaking @index spacebars command

### ISSUE THREAD

**Issue by joaobarcia** [matteodem/meteor-easy-search#366] opened 2015-11-18 12:47 UTC
Hi,

Spacebars now accepts @index command inside of an {{#each}} iterator. The new easy search seems to break this functionality as nothing is displayed. Even when outside of any easy search iterator.

Simplest case:
* create the todos example
* place @index inside any of the {{#each}} loops
* add easy search package

**Comment by Shogutora** [comment] 2015-11-19 06:41
+1

**Comment by joaobarcia** [comment] 2015-12-15 22:21
Any info regarding this?

Thanks

**Comment by matteodem** [comment] 2015-12-16 08:15
I'm not really sure what this is related to, might be an issue with spacebars scope. I'll have a look at this soon.

**Comment by joaobarcia** [comment] 2015-12-16 10:07
Hi Matt, I took a look at the file. Correct me if I'm wrong, but I would find it strange if it's possible to fix just through that template. The @index command is broken for every {{#each}} in the project, even when it's not an {{#EasySearch.Each}}. 

Maybe it's because easysearch is using "index" as a template parameter?

**Comment by matteodem** [comment] 2015-12-16 10:09
Which version of EasySearch are you using?

**Comment by joaobarcia** [comment] 2015-12-16 10:11
2.0.5

**Comment by kjarrith** [comment] 2015-12-18 20:00
+1

**Comment by kjarrith** [comment] 2015-12-18 20:20
Can confirm this is acting on every {{#each}} in the project - rendering @index undefined.

**Comment by kristjaningi** [comment] 2015-12-19 17:30
+1

**Comment by matteodem** [comment] 2015-12-23 15:07
Will have a look at this over the next days

**Comment by mitar** [comment] 2015-12-24 06:11
This is duplicate of #331.

You still haven't upgraded to [Blaze Components 0.15.1](https://github.com/matteodem/meteor-easy-search/blob/master/packages/easysearch:components/package.js#L14).

**Comment by mitar** [comment] 2015-12-24 06:17
This is an interesting problem. I see that you upgraded, but I also see that the latest version is not upgraded. And I do not find any commit in-between which would revert the upgrade. `git` strangeness?

**Comment by matteodem** [comment] 2015-12-24 10:50
I really don't know, I also remember changing the dependency. This should be fixed in the latest version `2.0.6`.

**Closed** 2015-12-24 10:50 UTC
Labels: bug

**Comment by joaobarcia** [comment] 2015-12-24 15:54
Great! It is working now.

Thank you for the christmas present :)
