### ISSUE TITLE
Compatibility with package: collection-helpers

### ISSUE THREAD

**Issue by warsamebashir** [matteodem/meteor-easy-search#65] opened 2014-11-25 04:16 UTC
I have a reproduction here: https://github.com/warsamebashir/easy-search-helpers-bug using the `easy-search-leaderboard` example where for whatever reason the `esEach` component doesn't recognize any helpers defined https://github.com/warsamebashir/easy-search-helpers-bug/blob/master/leaderboard.js#L6 and so doesn't display anything in the rendered template. I thought it had to do with the way I was using it but I think it may be related to the results being returned ? Any thoughts ?

**Comment by warsamebashir** [comment] 2015-01-06 16:41
@matteodem Thanks for all the help on this

**Comment by matteodem** [comment] 2015-01-06 18:04
I'll set my priority now on the reactive: false problem and then on yours.

**Comment by erasaur** [comment] 2015-01-06 20:21
Sorry, haven't had much time to look into this. I just checked out collection helpers and it seems like all the functionality relies on the collection transform function. Off the top of my head, could we run documents through the transform before publishing to the client? I'm trying to think of where that would fail down the line. But transforms are something we have to accommodate for anyway.

**Comment by matteodem** [comment] 2015-01-06 21:01
Sounds like that could work, I'll have a look tomorrow if I got time.

**Comment by matteodem** [comment] 2015-01-07 16:28
Switching to reactive: false in the leaderboard works. I think it's related to the collection-helpers

**Comment by warsamebashir** [comment] 2015-01-07 22:46
@matteodem In switching that property, i get the errors I displayed earlier. What in collection-helpers is causing issues ?

**Comment by matteodem** [comment] 2015-01-08 16:36
I don't know, I'd need a reproduction repository for that.

**Comment by warsamebashir** [comment] 2015-01-08 17:24
I guess I am a little confused. I provided on this issue a repro using `collection-helpers`, is that what was switched to `reactive:false` or the `collection-helpers` package was removed from the `leaderboard` example ?

**Comment by matteodem** [comment] 2015-01-08 19:55
I was talking about the reproduction for reactive: false, because when I tested it with the leaderboard example it worked. I'll try the same out with your reproduction repository, when I get to it.

**Comment by warsamebashir** [comment] 2015-01-09 17:42
@matteodem Thanks for taking another look. You're right in the repo I provided was outdated and has the wrong config, It was in my current application that has the `mongo-db` field set. I am not sure if there was a way i can install `easy-search` off the PR or wait and see if it will be merged.

**Comment by matteodem** [comment] 2015-01-09 18:27
I guess waiting is the only solution now. Otherwise I'll merge it tomorrow or on Sunday.

**Comment by matteodem** [comment] 2015-01-10 11:52
This is fixed in the latest version.

**Closed by matteodem** 2015-01-10 11:52 UTC
Labels: bug

**Comment by frankapimenta** [comment] 2016-05-20 15:48
is this reactive false option still supported?

**Comment by matteodem** [comment] 2016-05-22 09:48
No this option is not around anymore

**Comment by frankapimenta** [comment] 2016-05-22 18:15
Just as curiosity. Was there a strong reason to remove it? 
ATM I would really require it. And since I cannot control the publication of the index...how would I accomplish this without hacks?

**Comment by matteodem** [comment] 2016-05-23 06:57
Do you want to use the components? It would be possible to call the `search` method in a Meteor method, which is only called on the server and returns the docs (not the cursor).

**Comment by frankapimenta** [comment] 2016-05-26 15:08
I thought before about what you suggested (by using reactive: false) but I would like to use the components and avoid its manual implementation.
Is there a way to control the publication of the index?

**Comment by matteodem** [comment] 2016-05-27 09:27
Created a new issue that should replace this functionality.
